# -*- coding: utf-8 -*-
"""Regional-Sales-Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDwHrWAloHshD13uWcC_L_2WWlDAr0gB
"""

# Regional Sales Analytics — Superstore Dataset
# Olivia Bonnette
# Investigates regional revenue gaps, pricing inconsistencies, and
# uneven product distribution across US sales territories.

# ============================================================
# CELL 1: Install and import
# ============================================================

# !pip install duckdb  # Uncomment if running in Google Colab

import duckdb
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

print("Packages loaded.")

# ============================================================
# CELL 2: Load and clean data
# ============================================================

# Load raw data
# In Google Colab: upload train.csv using the folder icon on the left sidebar
df = pd.read_csv('/train.csv', encoding='latin1')

print(f"Raw dataset: {df.shape[0]:,} rows, {df.shape[1]} columns")
print(f"Columns: {df.columns.tolist()}")

# ============================================================
# CELL 3: Data validation and cleaning
# ============================================================

# Fix date parsing — dates are in DD/MM/YYYY format
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date']  = pd.to_datetime(df['Ship Date'],  dayfirst=True)

# Check for nulls
print("\nNull counts per column:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# Postal code has 11 nulls — acceptable, not used in regional analysis
# All other key fields are complete

# Validate regions
print(f"\nRegions present: {sorted(df['Region'].unique())}")
print(f"Categories present: {sorted(df['Category'].unique())}")
print(f"Date range: {df['Order Date'].min().date()} to {df['Order Date'].max().date()}")
print(f"Total rows after cleaning: {len(df):,}")

# Register with DuckDB for SQL analysis
con = duckdb.connect()
con.register('sales', df)

print("\nData loaded and validated.")

# ============================================================
# CELL 4: Regional revenue summary
# ============================================================

# Step 1: Understand the overall revenue distribution by region
# This is the starting point — we see a gap and then investigate why

region_summary = con.execute("""
    SELECT
        Region,
        ROUND(SUM(Sales), 2)                   AS total_revenue,
        COUNT(DISTINCT "Order ID")             AS total_orders,
        COUNT(DISTINCT "Customer ID")          AS unique_customers,
        ROUND(AVG(Sales), 2)                   AS avg_order_value,
        ROUND(SUM(Sales) / COUNT(DISTINCT "Customer ID"), 2) AS revenue_per_customer
    FROM sales
    GROUP BY Region
    ORDER BY total_revenue DESC
""").df()

print("Regional revenue summary:")
print(region_summary.to_string(index=False))

# Calculate the gap between top and bottom region
top_region    = region_summary.iloc[0]
bottom_region = region_summary.iloc[-1]
gap_pct = round((top_region['total_revenue'] - bottom_region['total_revenue'])
                / top_region['total_revenue'] * 100, 1)

print(f"\nRevenue gap between {top_region['Region']} and {bottom_region['Region']}: {gap_pct}%")
print("This gap is the starting point for our root cause investigation.")

# ============================================================
# CELL 5: Drill into revenue by category and region
# ============================================================

# Step 2: Break the gap down by product category to isolate where it comes from

category_region = con.execute("""
    SELECT
        Category,
        Region,
        ROUND(SUM(Sales), 2)          AS total_revenue,
        COUNT(DISTINCT "Order ID")    AS orders,
        ROUND(AVG(Sales), 2)          AS avg_order_value
    FROM sales
    GROUP BY Category, Region
    ORDER BY Category, total_revenue DESC
""").df()

print("Revenue by category and region:")
print(category_region.to_string(index=False))

# Pivot for easier comparison
category_pivot = category_region.pivot(
    index='Category', columns='Region', values='total_revenue'
).round(2)
print("\nPivoted category revenue by region:")
print(category_pivot.to_string())

# ============================================================
# CELL 6: Pricing inconsistency analysis by sub-category
# ============================================================

# Step 3: Look at average sale value by sub-category across regions
# Pricing inconsistencies show up as large differences in avg_order_value
# for the same product across different regions

pricing_analysis = con.execute("""
    SELECT
        "Sub-Category",
        ROUND(AVG(CASE WHEN Region = 'West'    THEN Sales END), 2) AS west_avg,
        ROUND(AVG(CASE WHEN Region = 'East'    THEN Sales END), 2) AS east_avg,
        ROUND(AVG(CASE WHEN Region = 'Central' THEN Sales END), 2) AS central_avg,
        ROUND(AVG(CASE WHEN Region = 'South'   THEN Sales END), 2) AS south_avg,
        ROUND(AVG(Sales), 2)                                        AS overall_avg,
        COUNT(*)                                                    AS total_transactions
    FROM sales
    GROUP BY "Sub-Category"
    ORDER BY overall_avg DESC
""").df()

# Calculate max pricing spread across regions for each sub-category
pricing_analysis['price_spread'] = (
    pricing_analysis[['west_avg', 'east_avg', 'central_avg', 'south_avg']]
    .apply(lambda row: round(
        (row.max() - row.min()) / row.mean() * 100, 1
    ), axis=1)
)

print("Pricing analysis by sub-category (avg sale value per region):")
print(pricing_analysis.sort_values('price_spread', ascending=False).to_string(index=False))

# Identify sub-categories with the largest pricing spread
print("\nTop 5 sub-categories with largest regional pricing inconsistencies:")
top_inconsistent = pricing_analysis.nlargest(5, 'price_spread')[
    ['Sub-Category', 'west_avg', 'east_avg', 'central_avg', 'south_avg', 'price_spread']
]
print(top_inconsistent.to_string(index=False))

# ============================================================
# CELL 7: Volume distribution analysis
# ============================================================

# Step 4: Check whether the gap is also driven by uneven volume distribution
# i.e. high-value products concentrated in certain regions

volume_distribution = con.execute("""
    SELECT
        "Sub-Category",
        SUM(CASE WHEN Region = 'West'    THEN 1 ELSE 0 END) AS west_count,
        SUM(CASE WHEN Region = 'East'    THEN 1 ELSE 0 END) AS east_count,
        SUM(CASE WHEN Region = 'Central' THEN 1 ELSE 0 END) AS central_count,
        SUM(CASE WHEN Region = 'South'   THEN 1 ELSE 0 END) AS south_count,
        COUNT(*)                                             AS total,
        ROUND(SUM(Sales), 2)                                AS total_revenue
    FROM sales
    GROUP BY "Sub-Category"
    ORDER BY total_revenue DESC
""").df()

# Calculate South's share of each sub-category
volume_distribution['south_share_pct'] = round(
    volume_distribution['south_count'] / volume_distribution['total'] * 100, 1
)
volume_distribution['west_share_pct'] = round(
    volume_distribution['west_count'] / volume_distribution['total'] * 100, 1
)

print("Volume distribution by sub-category:")
print(volume_distribution[['Sub-Category', 'west_count', 'east_count',
                            'central_count', 'south_count', 'total',
                            'south_share_pct']].to_string(index=False))

# ============================================================
# CELL 8: Root cause — focus on Machines sub-category
# ============================================================

# Machines shows the largest pricing spread across regions:
# South avg = $2,993 vs West avg = $1,088 — a 175% difference
# This is the primary pricing inconsistency driving the revenue gap

machines_analysis = con.execute("""
    SELECT
        Region,
        COUNT(*)                       AS transactions,
        ROUND(SUM(Sales), 2)          AS total_revenue,
        ROUND(AVG(Sales), 2)          AS avg_sale_value,
        ROUND(MIN(Sales), 2)          AS min_sale,
        ROUND(MAX(Sales), 2)          AS max_sale
    FROM sales
    WHERE "Sub-Category" = 'Machines'
    GROUP BY Region
    ORDER BY avg_sale_value DESC
""").df()

print("Machines sub-category deep dive:")
print(machines_analysis.to_string(index=False))

# Copiers also shows large spread
copiers_analysis = con.execute("""
    SELECT
        Region,
        COUNT(*)                       AS transactions,
        ROUND(SUM(Sales), 2)          AS total_revenue,
        ROUND(AVG(Sales), 2)          AS avg_sale_value
    FROM sales
    WHERE "Sub-Category" = 'Copiers'
    GROUP BY Region
    ORDER BY avg_sale_value DESC
""").df()

print("\nCopiers sub-category deep dive:")
print(copiers_analysis.to_string(index=False))

# ============================================================
# CELL 9: Revenue gap attribution
# ============================================================

# Quantify how much of the West-South gap is explained by
# Machines and Copiers pricing differences

gap_attribution = con.execute("""
    WITH region_subcat AS (
        SELECT Region, "Sub-Category",
               SUM(Sales) AS revenue,
               COUNT(*) AS transactions,
               AVG(Sales) AS avg_price
        FROM sales
        GROUP BY Region, "Sub-Category"
    ),
    west_baseline AS (
        SELECT "Sub-Category", avg_price AS west_avg_price
        FROM region_subcat WHERE Region = 'West'
    ),
    south_actual AS (
        SELECT r."Sub-Category",
               r.revenue AS south_revenue,
               r.transactions AS south_transactions,
               r.avg_price AS south_avg_price,
               w.west_avg_price,
               ROUND((r.avg_price - w.west_avg_price) * r.transactions, 2) AS pricing_effect
        FROM region_subcat r
        JOIN west_baseline w ON r."Sub-Category" = w."Sub-Category"
        WHERE r.Region = 'South'
    )
    SELECT "Sub-Category",
           south_revenue,
           south_transactions,
           ROUND(south_avg_price, 2) AS south_avg,
           ROUND(west_avg_price, 2)  AS west_avg,
           pricing_effect
    FROM south_actual
    ORDER BY ABS(pricing_effect) DESC
""").df()

print("Revenue gap attribution — pricing effect of each sub-category:")
print("(Positive = South charges more than West; Negative = South charges less)")
print(gap_attribution.to_string(index=False))

total_gap = region_summary.iloc[0]['total_revenue'] - region_summary.iloc[-1]['total_revenue']
print(f"\nTotal West-South revenue gap: ${total_gap:,.2f}")
print(f"Gap as % of West revenue: {gap_pct}%")

# ============================================================
# CELL 10: Visualizations
# ============================================================

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

# Define colors and regions
colors_region = ['#2C7BB6', '#1A9641', '#F07D02', '#D7191C']
regions = ['West', 'East', 'Central', 'South']

# Re-run machines analysis to make sure variable exists
machines_analysis = con.execute("""
    SELECT Region, COUNT(*) AS transactions,
           ROUND(SUM(Sales), 2) AS total_revenue,
           ROUND(AVG(Sales), 2) AS avg_sale_value,
           ROUND(MIN(Sales), 2) AS min_sale,
           ROUND(MAX(Sales), 2) AS max_sale
    FROM sales
    WHERE "Sub-Category" = 'Machines'
    GROUP BY Region
    ORDER BY avg_sale_value DESC
""").df()

# Re-run volume distribution to make sure variable exists
volume_distribution = con.execute("""
    SELECT "Sub-Category",
           SUM(CASE WHEN Region='West'    THEN 1 ELSE 0 END) AS west_count,
           SUM(CASE WHEN Region='East'    THEN 1 ELSE 0 END) AS east_count,
           SUM(CASE WHEN Region='Central' THEN 1 ELSE 0 END) AS central_count,
           SUM(CASE WHEN Region='South'   THEN 1 ELSE 0 END) AS south_count,
           COUNT(*) AS total, ROUND(SUM(Sales), 2) AS total_revenue
    FROM sales GROUP BY "Sub-Category" ORDER BY total_revenue DESC
""").df()
volume_distribution['south_share_pct'] = round(volume_distribution['south_count'] / volume_distribution['total'] * 100, 1)
volume_distribution['west_share_pct']  = round(volume_distribution['west_count']  / volume_distribution['total'] * 100, 1)

# Re-run category pivot
category_region = con.execute("""
    SELECT Category, Region, ROUND(SUM(Sales), 2) AS total_revenue
    FROM sales GROUP BY Category, Region ORDER BY Category, total_revenue DESC
""").df()
category_pivot = category_region.pivot(index='Category', columns='Region', values='total_revenue').round(2)

# Re-run region summary
region_summary = con.execute("""
    SELECT Region, ROUND(SUM(Sales), 2) AS total_revenue
    FROM sales GROUP BY Region ORDER BY total_revenue DESC
""").df()

# Build 2x2 grid
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Regional Sales Analytics — Superstore Dataset', fontsize=15, fontweight='bold')

# Chart 1: Regional revenue
ax1 = axes[0, 0]
bars = ax1.bar(region_summary['Region'], region_summary['total_revenue'], color=colors_region)
ax1.set_title('Total Revenue by Region', fontweight='bold')
ax1.set_ylabel('Total Revenue ($)')
ax1.set_ylim(0, region_summary['total_revenue'].max() * 1.15)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f'${x:,.0f}'))
for bar, val in zip(bars, region_summary['total_revenue']):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5000,
             f'${val:,.0f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# Chart 2: Revenue by category and region
ax2 = axes[0, 1]
categories = ['Furniture', 'Office Supplies', 'Technology']
x = np.arange(len(categories))
width = 0.2
for i, (region, color) in enumerate(zip(regions, colors_region)):
    vals = [category_pivot.loc[cat, region] if region in category_pivot.columns else 0 for cat in categories]
    ax2.bar(x + i * width, vals, width, label=region, color=color)
ax2.set_title('Revenue by Category and Region', fontweight='bold')
ax2.set_ylabel('Total Revenue ($)')
ax2.set_xticks(x + width * 1.5)
ax2.set_xticklabels(categories)
ax2.legend()
ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f'${x:,.0f}'))

# Chart 3: Machines pricing inconsistency
ax3 = axes[1, 0]
machine_colors = [colors_region[regions.index(r)] for r in machines_analysis['Region']]
bars3 = ax3.bar(machines_analysis['Region'], machines_analysis['avg_sale_value'], color=machine_colors)
ax3.set_title('Machines: Avg Sale Value by Region\n(Primary Pricing Inconsistency)', fontweight='bold')
ax3.set_ylabel('Average Sale Value ($)')
ax3.set_ylim(0, machines_analysis['avg_sale_value'].max() * 1.25)
ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f'${x:,.0f}'))
for bar, val in zip(bars3, machines_analysis['avg_sale_value']):
    ax3.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 30,
             f'${val:,.0f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
ax3.axhline(y=machines_analysis['avg_sale_value'].mean(), color='gray', linestyle='--',
            linewidth=1, label=f'Overall avg (${machines_analysis["avg_sale_value"].mean():,.0f})')
ax3.legend()

# Chart 4: South vs West volume share — side by side bars
ax4 = axes[1, 1]
top_subcats = volume_distribution.nlargest(10, 'total_revenue').copy()
top_subcats = top_subcats.sort_values('south_share_pct')
y = np.arange(len(top_subcats))
height = 0.35
ax4.barh(y + height/2, top_subcats['south_share_pct'], height,
         color='#D7191C', alpha=0.85, label='South share %')
ax4.barh(y - height/2, top_subcats['west_share_pct'], height,
         color='#2C7BB6', alpha=0.85, label='West share %')
ax4.set_yticks(y)
ax4.set_yticklabels(top_subcats['Sub-Category'])
ax4.set_title('South vs West Volume Share\n(Top 10 Sub-Categories by Revenue)', fontweight='bold')
ax4.set_xlabel('% Share of Transactions')
ax4.axvline(x=25, color='gray', linestyle='--', linewidth=1, label='25% equal share baseline')
ax4.legend(loc='lower right')

plt.tight_layout()
plt.savefig('regional_sales_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved.")

# ============================================================
# CELL 11: Export clean tables for Power BI
# ============================================================

# Fact table
fact_sales = df[['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
                  'Customer ID', 'Customer Name', 'Segment', 'Country',
                  'City', 'State', 'Region', 'Product ID', 'Category',
                  'Sub-Category', 'Product Name', 'Sales']].copy()

# Dimension: region summary
dim_region = region_summary.copy()

# Dimension: category performance by region
dim_category_region = category_region.copy()

# Dimension: pricing analysis
dim_pricing = pricing_analysis.copy()

# Dimension: monthly revenue by region
df['order_month'] = df['Order Date'].dt.to_period('M').astype(str)
dim_monthly = df.groupby(['order_month', 'Region'])['Sales'].sum().reset_index()
dim_monthly.columns = ['month', 'region', 'total_revenue']
dim_monthly = dim_monthly.round(2)

# Export all
fact_sales.to_csv('fact_sales.csv', index=False)
dim_region.to_csv('dim_region_summary.csv', index=False)
dim_category_region.to_csv('dim_category_region.csv', index=False)
dim_pricing.to_csv('dim_pricing_analysis.csv', index=False)
dim_monthly.to_csv('dim_monthly_revenue.csv', index=False)
volume_distribution.to_csv('dim_volume_distribution.csv', index=False)
gap_attribution.to_csv('gap_attribution.csv', index=False)

print("All tables exported:")
print("  fact_sales.csv")
print("  dim_region_summary.csv")
print("  dim_category_region.csv")
print("  dim_pricing_analysis.csv")
print("  dim_monthly_revenue.csv")
print("  dim_volume_distribution.csv")
print("  gap_attribution.csv")
print("\nDownload these files and import into Power BI Desktop.")

# ============================================================
# CELL 12: Download all files (Google Colab only)
# ============================================================

from google.colab import files
import os

export_files = [
    'fact_sales.csv', 'dim_region_summary.csv', 'dim_category_region.csv',
    'dim_pricing_analysis.csv', 'dim_monthly_revenue.csv',
    'dim_volume_distribution.csv', 'gap_attribution.csv',
    'regional_sales_analysis.png'
]

for f in export_files:
    if os.path.exists(f):
        files.download(f)
        print(f"Downloaded: {f}")
